// All localized content for Dovilio's page
window.CONTENT = {
  pt: {
    role: "Analista de Testes / Engenharia",
    tagline: "Testes automatizados, sistemas HiL e integração veicular para a indústria automotiva.",
    location: "São Paulo, Brasil",
    status: "Disponível para novas oportunidades",
    sections: {
      about: "Sobre",
      experience: "Experiência",
      skills: "Competências",
      languages: "Idiomas",
      education: "Formação",
      certifications: "Certificações",
      interests: "Interesses",
      contact: "Contato",
      download: "Baixar CV (PDF)",
    },
    about: {
      title: "Objetivo",
      body: "Engenheiro em formação com experiência em testes automotivos HiL/RPP, automação com Python e colaboração internacional com equipes de engenharia na Alemanha. Busco posições que me permitam evoluir tecnicamente e agregar valor mensurável ao negócio.",
    },
    experience: [
      {
        role: "Analista de Testes",
        company: "IAV do Brasil Ltda.",
        location: "São Paulo, Brasil",
        period: "Out 2021 — Presente",
        status: "Atual",
        bullets: [
          { label: "Automação & Gestão", text: "Criação e coordenação de tickets KPM via JIRA; posterior automação do processo de abertura utilizando Python." },
          { label: "Testes HiL / RPP", text: "Testes de componente e integração em bancadas HiL e RPP para veículos VW (mercado europeu). Experiência com NovaCarts, DSPACE e análise de dados via CANoe." },
          { label: "Colaboração internacional", text: "Integração ao projeto pioneiro de testes remotos, coordenando atividades entre equipes globais e hardware localizado na Alemanha." },
          { label: "Capacitação técnica", text: "Treinamento intensivo de 4 semanas na unidade VW em Wolfsburg, focado em operação de bancadas e metodologias de simulação." },
          { label: "Gestão do conhecimento", text: "Estruturação de base de conhecimento no Confluence, centralizando documentações técnicas e alinhamentos com a engenharia alemã." },
        ],
      },
      {
        role: "Estágio em Engenharia",
        company: "Mercedes-Benz do Brasil",
        location: "São Bernardo do Campo, Brasil",
        period: "Jan 2015 — Dez 2016",
        status: "",
        bullets: [
          { label: "Manutenção & documentação", text: "Gestão de planos de manutenção preventiva via SAP e tradução técnica de manuais para novos equipamentos." },
          { label: "Análise de falhas", text: "Coordenação de reuniões de Análise de Causa Raiz (RCA) para solucionar interrupções no fluxo produtivo." },
          { label: "Gestão de pessoas", text: "Desenvolvimento de sistema de controle de indicadores para monitoramento e validade de treinamentos da equipe." },
        ],
      },
    ],
    skills: {
      technical: [
        { k: "HiL / RPP", v: "Bancadas de teste" },
        { k: "NovaCarts", v: "Simulação" },
        { k: "DSPACE", v: "Hardware-in-the-Loop" },
        { k: "CANoe", v: "Análise CAN" },
        { k: "Python", v: "Automação" },
        { k: "JIRA", v: "Gestão de tickets" },
        { k: "Confluence", v: "Documentação" },
        { k: "SAP", v: "Manutenção" },
      ],
      soft: ["Assertividade", "Capacidade de motivar", "Trabalho em equipe", "Comunicação multicultural"],
    },
    languages: [
      { lang: "Português", level: "Nativo", inst: "" },
      { lang: "Inglês", level: "Avançado", inst: "Instituto Richard FISK" },
      { lang: "Alemão", level: "Avançado", inst: "Steigenberger Schule" },
      { lang: "Espanhol", level: "Avançado", inst: "Instituto Richard FISK" },
    ],
    education: [
      { degree: "Bacharelado em Ciência e Tecnologia", school: "Universidade Federal do ABC", year: "2026" },
    ],
    certifications: [
      { name: "Certified Tester Foundation Level (CTFL)", issuer: "ISTQB" },
      { name: "Treinamento sobre Redes CAN e CANoe", issuer: "Vector" },
      { name: "Curso de Formação de Professores", issuer: "FISK" },
    ],
    interests: [
      { k: "Aeromodelismo", v: "Construção e pilotagem" },
      { k: "Ciclismo", v: "Longas distâncias" },
      { k: "Gastronomia", v: "Cozinhar e descobrir" },
    ],
    contact: {
      email: "dovilio.neto13@gmail.com",
      phone: "+55 11 98652 7912",
      linkedin: "linkedin.com/in/dovilio-ferrari-neto-066087213",
      linkedinUrl: "https://www.linkedin.com/in/dovilio-ferrari-neto-066087213/",
    },
    ui: {
      copy: "Copiar",
      copied: "Copiado",
      openLinkedIn: "Abrir LinkedIn",
      sendEmail: "Enviar email",
      call: "Ligar",
      scrollHint: "Role para continuar",
      yearsExperience: "anos de experiência",
      projectsDelivered: "projeto de testes remotos",
      languagesSpoken: "idiomas falados",
      continents: "continentes colaborados",
    },
  },
  en: {
    role: "Test Engineer / QA Engineering",
    tagline: "Automated testing, HiL systems and vehicle integration for the automotive industry.",
    location: "São Paulo, Brazil",
    status: "Open to new opportunities",
    sections: {
      about: "About",
      experience: "Experience",
      skills: "Skills",
      languages: "Languages",
      education: "Education",
      certifications: "Certifications",
      interests: "Interests",
      contact: "Contact",
      download: "Download CV (PDF)",
    },
    about: {
      title: "Objective",
      body: "Engineering-track professional with hands-on experience in automotive HiL/RPP testing, Python automation and international collaboration with German engineering teams. Seeking roles that let me grow technically while delivering measurable value.",
    },
    experience: [
      {
        role: "Test Analyst",
        company: "IAV do Brasil Ltda.",
        location: "São Paulo, Brazil",
        period: "Oct 2021 — Present",
        status: "Current",
        bullets: [
          { label: "Automation & management", text: "Created and coordinated KPM tickets through JIRA; later automated the ticket-opening process using Python." },
          { label: "HiL / RPP testing", text: "Component and integration testing on HiL and RPP benches for VW vehicles (European market). Experience with NovaCarts, DSPACE and CAN data analysis via CANoe." },
          { label: "International collaboration", text: "Joined the pioneering remote-testing project, coordinating activities across global teams and hardware based in Germany." },
          { label: "Technical training", text: "4-week intensive training at VW Wolfsburg, focused on bench operation and simulation methodologies." },
          { label: "Knowledge management", text: "Built and maintained a Confluence knowledge base centralising technical documentation and alignments with the German engineering team." },
        ],
      },
      {
        role: "Engineering Intern",
        company: "Mercedes-Benz do Brasil",
        location: "São Bernardo do Campo, Brazil",
        period: "Jan 2015 — Dec 2016",
        status: "",
        bullets: [
          { label: "Maintenance & documentation", text: "Managed preventive maintenance plans through SAP and translated technical manuals for new equipment." },
          { label: "Failure analysis", text: "Coordinated Root Cause Analysis (RCA) meetings to resolve production-line disruptions." },
          { label: "People management", text: "Developed a KPI control system to monitor training validity across the team." },
        ],
      },
    ],
    skills: {
      technical: [
        { k: "HiL / RPP", v: "Test benches" },
        { k: "NovaCarts", v: "Simulation" },
        { k: "DSPACE", v: "Hardware-in-the-Loop" },
        { k: "CANoe", v: "CAN analysis" },
        { k: "Python", v: "Automation" },
        { k: "JIRA", v: "Ticket management" },
        { k: "Confluence", v: "Documentation" },
        { k: "SAP", v: "Maintenance" },
      ],
      soft: ["Assertive", "Motivates teams", "Team player", "Cross-cultural communication"],
    },
    languages: [
      { lang: "Portuguese", level: "Native", inst: "" },
      { lang: "English", level: "Advanced", inst: "Instituto Richard FISK" },
      { lang: "German", level: "Advanced", inst: "Steigenberger Schule" },
      { lang: "Spanish", level: "Advanced", inst: "Instituto Richard FISK" },
    ],
    education: [
      { degree: "B.Sc. in Science and Technology", school: "Federal University of ABC (UFABC)", year: "2026" },
    ],
    certifications: [
      { name: "Certified Tester Foundation Level (CTFL)", issuer: "ISTQB" },
      { name: "CAN Networks and CANoe Training", issuer: "Vector" },
      { name: "Teacher Training Course", issuer: "FISK" },
    ],
    interests: [
      { k: "RC Aircraft", v: "Build and fly" },
      { k: "Cycling", v: "Long distance" },
      { k: "Cooking", v: "Cook and discover" },
    ],
    contact: {
      email: "dovilio.neto13@gmail.com",
      phone: "+55 11 98652 7912",
      linkedin: "linkedin.com/in/dovilio-ferrari-neto-066087213",
      linkedinUrl: "https://www.linkedin.com/in/dovilio-ferrari-neto-066087213/",
    },
    ui: {
      copy: "Copy",
      copied: "Copied",
      openLinkedIn: "Open LinkedIn",
      sendEmail: "Send email",
      call: "Call",
      scrollHint: "Scroll to continue",
      yearsExperience: "years of experience",
      projectsDelivered: "remote-testing project",
      languagesSpoken: "languages spoken",
      continents: "continents collaborated",
    },
  },
  de: {
    role: "Testingenieur / QA-Engineering",
    tagline: "Automatisiertes Testen, HiL-Systeme und Fahrzeugintegration für die Automobilindustrie.",
    location: "São Paulo, Brasilien",
    status: "Offen für neue Möglichkeiten",
    sections: {
      about: "Über",
      experience: "Erfahrung",
      skills: "Kompetenzen",
      languages: "Sprachen",
      education: "Ausbildung",
      certifications: "Zertifizierungen",
      interests: "Interessen",
      contact: "Kontakt",
      download: "Lebenslauf herunterladen (PDF)",
    },
    about: {
      title: "Ziel",
      body: "Ingenieur in Ausbildung mit praktischer Erfahrung in automobilem HiL/RPP-Testing, Python-Automatisierung und internationaler Zusammenarbeit mit deutschen Engineering-Teams. Suche Positionen, die technisches Wachstum und messbaren Geschäftswert ermöglichen.",
    },
    experience: [
      {
        role: "Testanalyst",
        company: "IAV do Brasil Ltda.",
        location: "São Paulo, Brasilien",
        period: "Okt. 2021 — heute",
        status: "Aktuell",
        bullets: [
          { label: "Automatisierung & Management", text: "Erstellung und Koordination von KPM-Tickets über JIRA; spätere Automatisierung des Prozesses mit Python." },
          { label: "HiL / RPP-Tests", text: "Komponenten- und Integrationstests auf HiL- und RPP-Prüfständen für VW-Fahrzeuge (europäischer Markt). Erfahrung mit NovaCarts, DSPACE und Datenanalyse über CANoe." },
          { label: "Internationale Zusammenarbeit", text: "Teilnahme am Pionierprojekt für Remote-Tests; Koordination zwischen globalen Teams und Hardware in Deutschland." },
          { label: "Technische Weiterbildung", text: "4-wöchiges Intensivtraining bei VW in Wolfsburg mit Fokus auf Prüfstandsbetrieb und Simulationsmethoden." },
          { label: "Wissensmanagement", text: "Aufbau und Pflege einer Confluence-Wissensbasis zur zentralen Ablage technischer Dokumentation und Abstimmungen mit der deutschen Engineering-Seite." },
        ],
      },
      {
        role: "Praktikant Ingenieurwesen",
        company: "Mercedes-Benz do Brasil",
        location: "São Bernardo do Campo, Brasilien",
        period: "Jan. 2015 — Dez. 2016",
        status: "",
        bullets: [
          { label: "Wartung & Dokumentation", text: "Verwaltung präventiver Wartungspläne über SAP und technische Übersetzung von Handbüchern neuer Anlagen." },
          { label: "Fehleranalyse", text: "Koordination von Root-Cause-Analysis-Meetings zur Behebung von Produktionsunterbrechungen." },
          { label: "Personalmanagement", text: "Entwicklung eines KPI-Systems zur Überwachung der Gültigkeit der Team-Schulungen." },
        ],
      },
    ],
    skills: {
      technical: [
        { k: "HiL / RPP", v: "Prüfstände" },
        { k: "NovaCarts", v: "Simulation" },
        { k: "DSPACE", v: "Hardware-in-the-Loop" },
        { k: "CANoe", v: "CAN-Analyse" },
        { k: "Python", v: "Automatisierung" },
        { k: "JIRA", v: "Ticket-Management" },
        { k: "Confluence", v: "Dokumentation" },
        { k: "SAP", v: "Wartung" },
      ],
      soft: ["Durchsetzungsstark", "Motivierend", "Teamplayer", "Interkulturelle Kommunikation"],
    },
    languages: [
      { lang: "Portugiesisch", level: "Muttersprache", inst: "" },
      { lang: "Englisch", level: "Fortgeschritten", inst: "Instituto Richard FISK" },
      { lang: "Deutsch", level: "Fortgeschritten", inst: "Steigenberger Schule" },
      { lang: "Spanisch", level: "Fortgeschritten", inst: "Instituto Richard FISK" },
    ],
    education: [
      { degree: "B.Sc. Wissenschaft und Technologie", school: "Bundesuniversität ABC (UFABC)", year: "2026" },
    ],
    certifications: [
      { name: "Certified Tester Foundation Level (CTFL)", issuer: "ISTQB" },
      { name: "CAN-Netzwerke und CANoe Training", issuer: "Vector" },
      { name: "Lehrer-Ausbildungskurs", issuer: "FISK" },
    ],
    interests: [
      { k: "Modellflug", v: "Bau und Flug" },
      { k: "Radsport", v: "Langstrecke" },
      { k: "Kochen", v: "Entdecken und kochen" },
    ],
    contact: {
      email: "dovilio.neto13@gmail.com",
      phone: "+55 11 98652 7912",
      linkedin: "linkedin.com/in/dovilio-ferrari-neto-066087213",
      linkedinUrl: "https://www.linkedin.com/in/dovilio-ferrari-neto-066087213/",
    },
    ui: {
      copy: "Kopieren",
      copied: "Kopiert",
      openLinkedIn: "LinkedIn öffnen",
      sendEmail: "E-Mail senden",
      call: "Anrufen",
      scrollHint: "Weiterscrollen",
      yearsExperience: "Jahre Erfahrung",
      projectsDelivered: "Remote-Testprojekt",
      languagesSpoken: "Sprachen",
      continents: "Kontinente Zusammenarbeit",
    },
  },
};
